### ISSUE TITLE
My project (libtorch c++) is ISO C++14 Standard (/std:c++14)

### ISSUE THREAD

**Issue by QuantScientist** [Siv3D/OpenSiv3D#532]
However, you require std:c++latest when using VC. 
Anyway this can be resolved? 
I am trying to integrate both libraries.

**Comment by Reputeless** [comment]
solution:
https://discuss.pytorch.org/t/libtorch-c-17-visual-studio/73793

`/std:c++latest` is mandatory when using OpenSiv3D headers.

**Comment by QuantScientist** [comment]
This only works with std++17, while Siv3d is std++latest. libtorch does not compile with that. 

![image](https://user-images.githubusercontent.com/18743986/93314367-5527e880-f812-11ea-9699-7ef315d1fcfb.png)

**Comment by QuantScientist** [comment]
Is it possible to download an old version of Siv3d that works with std++17 / 14? 
Thanks!

**Comment by Reputeless** [comment]
You can use OpenSiv3D v0.4.3 with std:c++17 by removing some lines of code from `Siv3D/Format.hpp`.

![image](https://user-images.githubusercontent.com/3108136/93559810-8d1e5f80-f9bb-11ea-8f42-df2c7d20f045.png)

This workaround may not work with later versions of OpenSiv3D since they will use more C++20 features.

**Comment by QuantScientist** [comment]
Thank you so much for your help. I shall write a post + git repo about the integration of Siv3D + GPU  + Libtorch.
